import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/Header";
//
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//


async function globalLoader(){

  const path = '/api/global?populate[header][populate][navLinks]=true';
  const BASE_URL = 'http://localhost:1337';
  const url = new URL(path,BASE_URL); 

  const response = await fetch(url.href);
  const data = await response.json();

  // console.log(data);
  return { ...data.data };
}



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const global = await globalLoader();

  const navLinks:[] = global.header.navLinks;

  // console.log(navLinks);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header navLinks={navLinks}/>
        {children}
      </body>
    </html>
  );
}
